/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.admin;

import gui.dashboards.AdminBoard;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import json.JsonCoursesDatabase;
import json.JsonUserDatabase;
import logic.userRole.AdminRole;
import model.course.Course;
import model.course.CourseStatus;
import static model.course.CourseStatus.PENDING;

import model.user.Admin;

/**
 *
 * @author Nour
 */
public class PendingList extends javax.swing.JFrame {

    private Admin a;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PendingList.class.getName());

    /**
     * Creates new form PendingList
     *
     * @param a
     */
    public PendingList(Admin a) {
        this.a = a;
        initComponents();
        viewPendingCourses(a);
    }

    public void viewPendingCourses(Admin a) {
        AdminRole A = new AdminRole();
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        d.setRowCount(0);

        // Get all courses
        List<Course> allCourses = A.viewCourses(a);
        CourseStatus cs = PENDING;

        for (Course course : allCourses) {

            if (course.getApprovalStatus() == cs) {
                Object[] row = new Object[]{
                    course.getCourseId(),
                    course.getTitle()
                };
                d.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Decline");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Approve");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 199, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(110, 110, 110)
                        .addComponent(jButton2)
                        .addGap(126, 126, 126)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to approve", "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) jTable1.getValueAt(selectedRow, 0);
        String courseTitle = (String) jTable1.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Do you want to approve the course: " + courseTitle + "?",
                "Confirm Approval",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                JsonCoursesDatabase courseDB = new JsonCoursesDatabase("courses.json");
                List<Course> allCourses = courseDB.getCourses();
                AdminRole am = new AdminRole();
                for (Course course : allCourses) {
                    if (course.getCourseId().equals(courseId)) {
                        am.approveCourse(course);
                        String today = java.time.LocalDate.now().toString();
                        a.addApproval(courseId, "APPROVED", today);

                        break;
                    }
                }
                courseDB.setCourses(allCourses);
                courseDB.saveToFile("courses.json");

                JsonUserDatabase userDB = new JsonUserDatabase("users.json");
                List<Admin> admins = userDB.getAdmins();

                for (int i = 0; i < admins.size(); i++) {
                    if (admins.get(i).getUserId() == a.getUserId()) {
                        admins.set(i, a);   // replace old admin with updated one
                        break;
                    }
                }

                userDB.setAdmins(admins);
                userDB.saveToFile("users.json");

                JOptionPane.showMessageDialog(this, "Course approved: " + courseTitle, "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                
                viewPendingCourses(a);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error approving course: " + e.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to approve", "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) jTable1.getValueAt(selectedRow, 0);
        String courseTitle = (String) jTable1.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Do you want to reject the course: " + courseTitle + "?",
                "Confirm Rejection",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                JsonCoursesDatabase courseDB = new JsonCoursesDatabase("courses.json");
                List<Course> allCourses = courseDB.getCourses();
                AdminRole am = new AdminRole();
                for (Course course : allCourses) {
                    if (course.getCourseId().equals(courseId)) {
                        am.rejectCourse(course);
                        String today = java.time.LocalDate.now().toString();
                        a.addApproval(courseId, "REJECTED", today);
                        break;
                    }
                }

                courseDB.setCourses(allCourses);
                courseDB.saveToFile("courses.json");
                JsonUserDatabase userDB = new JsonUserDatabase("users.json");
                List<Admin> admins = userDB.getAdmins();

                for (int i = 0; i < admins.size(); i++) {
                    if (admins.get(i).getUserId() == a.getUserId()) {
                        admins.set(i, a);   // replace old admin with updated one
                        break;
                    }
                }

                userDB.setAdmins(admins);
                userDB.saveToFile("users.json");

                JOptionPane.showMessageDialog(this, "Course rejected: " + courseTitle, "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                
                viewPendingCourses(a);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error approving course: " + e.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        AdminBoard c;
        c = new AdminBoard(a);
        c.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
