/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.student;

import gui.dashboards.StudentBoard;
import model.course.Course;
import model.user.Student;
import logic.admin.StudentRole;
import json.JsonUserReader;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AltAWKEl
 */
public class EnrollCourses extends javax.swing.JFrame {
    private Student s;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(EnrollCourses.class.getName());

    /**
     * Creates new form EnrollCourses
     */
    public EnrollCourses(Student s) {
        this.s = s;
        initComponents();
        loadAvailableCourses();
    }

    private void loadAvailableCourses() {
        StudentRole sr = new StudentRole();
        DefaultTableModel model = (DefaultTableModel) coursesTable.getModel();
        model.setRowCount(0);

        List<Course> allCourses = sr.viewCourses(s);
        List<String> enrolledCourses = s.getEnrolledCourses();

        for (Course course : allCourses) {
            // Only show courses the student is NOT enrolled in
            if (enrolledCourses == null || !enrolledCourses.contains(course.getCourseId())) {
                model.addRow(new Object[] {
                        course.getCourseId(),
                        course.getTitle(),
                        course.getDescription()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enrollBtnActionPerformed
        int selectedRow = coursesTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to enroll in", "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) coursesTable.getValueAt(selectedRow, 0);
        String courseTitle = (String) coursesTable.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Do you want to enroll in: " + courseTitle + "?",
                "Confirm Enrollment",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Add course to student's enrolled courses
            s.getEnrolledCourses().add(courseId);

            // Save to file
            JsonUserReader userReader = new JsonUserReader("users.json");
            List<model.user.Student> students = userReader.getStudents();

            for (int i = 0; i < students.size(); i++) {
                if (students.get(i).getUserId() == s.getUserId()) {
                    students.set(i, s);
                    break;
                }
            }

            userReader.setStudents(students);
            userReader.saveToFile("users.json");

            JOptionPane.showMessageDialog(this, "Successfully enrolled in: " + courseTitle, "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            // Reload the table
            loadAvailableCourses();
        }
    }// GEN-LAST:event_enrollBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new StudentBoard(s).setVisible(true);
    }// GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
