/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.student;

import gui.dashboards.StudentBoard;
import java.util.ArrayList;
import model.course.Course;
import model.user.Student;
import logic.userRole.StudentRole;
import json.JsonUserDatabase;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import json.JsonCoursesDatabase;
import model.course.CourseProgress;
import model.course.CourseStatus;
import static model.course.CourseStatus.APPROVED;
import model.course.Lesson;
import model.course.LessonProgress;
import model.user.User;

/**
 *
 * @author AltAWKEl
 */
public class EnrollCourses extends javax.swing.JFrame {
    private Student s;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(EnrollCourses.class.getName());

    /**
     * Creates new form EnrollCourses
     */
    public EnrollCourses(Student s) {
        this.s = s;
        initComponents();
        loadAvailableCourses();
    }

    private void loadAvailableCourses() {
        StudentRole sr = new StudentRole();
        DefaultTableModel model = (DefaultTableModel) coursesTable.getModel();
        model.setRowCount(0);

        List<Course> allCourses = sr.viewCourses(s);
        List<String> enrolledCourses = s.getEnrolledCourses();
CourseStatus cs = APPROVED;
        for (Course course : allCourses) {
            // Only show courses the student is NOT enrolled in
            if ((enrolledCourses == null || !enrolledCourses.contains(course.getCourseId()))&& course.getApprovalStatus()== cs) {
                model.addRow(new Object[] {
                        course.getCourseId(),
                        course.getTitle(),
                        course.getDescription()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        enrollBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enroll in Courses");

        coursesTable.setBackground(new java.awt.Color(204, 255, 255));
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "Course ID", "Title", "Description"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(coursesTable);

        enrollBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enrollBtn.setText("Enroll in Selected Course");
        enrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setText("Back to Dashboard");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(enrollBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(enrollBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enrollBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enrollBtnActionPerformed
        int selectedRow = coursesTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to enroll in", "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) coursesTable.getValueAt(selectedRow, 0);
        String courseTitle = (String) coursesTable.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Do you want to enroll in: " + courseTitle + "?",
                "Confirm Enrollment",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Add course to student's enrolled courses
            s.getEnrolledCourses().add(courseId);
            
            JsonCoursesDatabase coursesReader=new JsonCoursesDatabase("courses.json");
            List<Course> courses=coursesReader.getCourses();
            Course temp=null;
            for(Course course:courses)
            {if(course.getCourseId().equals(courseId))
                {temp=course; break;}}
            temp.getStudents().add(s.getUserId());
            
            List<Lesson>lessons=temp.getLessons();
            ArrayList<LessonProgress>lessonProgress = new ArrayList<>();
            CourseProgress courseProgress=new CourseProgress(courseId);
            for(Lesson lesson:lessons)
            {LessonProgress progress=new LessonProgress(lesson.getLessonId(), 0, false);
            lessonProgress.add(progress);}
            courseProgress.setLessonProgress(lessonProgress);
            s.getProgress().add(courseProgress);
            
            coursesReader.setCourses(courses);
coursesReader.saveToFile("courses.json");
            // Save to file
            JsonUserDatabase userReader = new JsonUserDatabase("users.json");
            List<Student> students = userReader.getStudents();

            for (int i = 0; i < students.size(); i++) {
                if (students.get(i).getUserId() == s.getUserId()) {
                    students.set(i, s);
                    break;
                }
            }

            userReader.setStudents(students);
            userReader.saveToFile("users.json");

            JOptionPane.showMessageDialog(this, "Successfully enrolled in: " + courseTitle, "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            // Reload the table
            loadAvailableCourses();
        }
    }// GEN-LAST:event_enrollBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new StudentBoard(s).setVisible(true);
    }// GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable coursesTable;
    private javax.swing.JButton enrollBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
